export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const IS_UNIQUE_DOMAIN = "IS_UNIQUE_DOMAIN";
export const INSERT_OWNER_LOGIN = "INSERT_OWNER_LOGIN";
export const CREATE_IPFS = "CREATE_IPFS";
export const INSERT_OWNER_DOMAIN = "INSERT_OWNER_DOMAIN";
export const LOGIN_WALLET = "LOGIN_WALLET";

export const GET_DOMAINS_OWNER = "GET_DOMAINS_OWNER";